from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
import xml.etree.ElementTree as ET
from typing import Tuple


@dataclass
class RouteScalingReport:
    base_estimated_vehicles: float
    target_vehicles: int
    scale_factor: float
    mode: str  # "flows" or "vehicles"
    notes: str


def _estimate_total_vehicles(root: ET.Element) -> Tuple[float, str]:
    """
    Estimate the total number of vehicles generated by this route file.

    Supports:
      - explicit <vehicle> and <trip> elements (count exact)
      - <flow number="..."> (sum exact)
      - <flow vehsPerHour="..."> with begin/end (estimate)
      - <flow probability="..."> with begin/end (estimate = prob * seconds)
    """
    vehicles = root.findall(".//vehicle")
    trips = root.findall(".//trip")
    if vehicles or trips:
        return float(len(vehicles) + len(trips)), "vehicles"

    flows = root.findall(".//flow")
    if flows:
        total = 0.0
        notes = []
        for f in flows:
            if "number" in f.attrib:
                total += float(f.attrib["number"])
            else:
                begin = float(f.attrib.get("begin", "0"))
                end = float(f.attrib.get("end", begin))
                duration = max(0.0, end - begin)
                if "vehsPerHour" in f.attrib:
                    vph = float(f.attrib["vehsPerHour"])
                    total += vph * (duration / 3600.0)
                elif "probability" in f.attrib:
                    p = float(f.attrib["probability"])
                    total += p * duration
                else:
                    notes.append("flow missing number/vehsPerHour/probability; counted as 0")
        mode = "flows"
        return total, mode

    return 0.0, "unknown"


def scale_route_file(
    base_route_path: Path,
    output_route_path: Path,
    target_vehicles: int,
) -> RouteScalingReport:
    """
    Create a scaled version of a SUMO route file to approximate target demand.

    Strategy:
    - If file uses <vehicle>/<trip>: keep earliest N, or if N > base, loop+duplicate with new IDs.
    - If file uses <flow>: scale flow params (number, vehsPerHour, probability) by a factor.
    """
    tree = ET.parse(base_route_path)
    root = tree.getroot()

    base_est, mode = _estimate_total_vehicles(root)
    if base_est <= 0:
        raise ValueError(
            f"Could not estimate vehicles from {base_route_path}. "
            f"Expected <vehicle>, <trip>, or <flow> elements."
        )

    factor = float(target_vehicles) / float(base_est)

    if mode == "flows":
        for f in root.findall(".//flow"):
            if "number" in f.attrib:
                f.attrib["number"] = str(int(round(float(f.attrib["number"]) * factor)))
            elif "vehsPerHour" in f.attrib:
                f.attrib["vehsPerHour"] = str(float(f.attrib["vehsPerHour"]) * factor)
            elif "probability" in f.attrib:
                p = float(f.attrib["probability"]) * factor
                # Keep prob in [0,1] to avoid invalid config; if it saturates, it implies max insertion rate.
                f.attrib["probability"] = str(min(1.0, p))

        notes = "Scaled flow parameters by factor; probability capped at 1.0."
        output_route_path.parent.mkdir(parents=True, exist_ok=True)
        tree.write(output_route_path, encoding="utf-8", xml_declaration=True)
        return RouteScalingReport(base_est, target_vehicles, factor, mode, notes)

    # mode == "vehicles"
    vehicles = root.findall(".//vehicle")
    trips = root.findall(".//trip")
    elems = vehicles + trips

    # Sort by depart if present
    def depart_time(e: ET.Element) -> float:
        return float(e.attrib.get("depart", "0"))

    elems_sorted = sorted(elems, key=depart_time)

    # Remove all explicit vehicles/trips, then re-add desired list
    for e in elems:
        parent = root
        # <routes> usually owns them directly, so remove from root
        try:
            root.remove(e)
        except ValueError:
            # if nested, do nothing (rare)
            pass

    chosen = []
    if target_vehicles <= len(elems_sorted):
        chosen = elems_sorted[:target_vehicles]
        notes = "Trimmed explicit vehicles/trips to match target."
    else:
        # Duplicate by looping with new IDs and slight depart offsets
        chosen = list(elems_sorted)
        remaining = target_vehicles - len(elems_sorted)
        dup_index = 0
        while remaining > 0:
            base_elem = elems_sorted[dup_index % len(elems_sorted)]
            new_elem = ET.fromstring(ET.tostring(base_elem, encoding="unicode"))
            # Update ID
            old_id = new_elem.attrib.get("id", f"veh_{dup_index}")
            new_elem.attrib["id"] = f"{old_id}_dup{dup_index}"
            # Slightly shift depart to avoid exact collisions
            if "depart" in new_elem.attrib:
                new_elem.attrib["depart"] = str(float(new_elem.attrib["depart"]) + 0.1 * (dup_index + 1))
            chosen.append(new_elem)
            dup_index += 1
            remaining -= 1
        notes = "Duplicated explicit vehicles/trips to reach target; depart times slightly offset."

    # Add chosen back
    for e in chosen:
        root.append(e)

    output_route_path.parent.mkdir(parents=True, exist_ok=True)
    tree.write(output_route_path, encoding="utf-8", xml_declaration=True)
    return RouteScalingReport(base_est, target_vehicles, factor, mode, notes)
